development:
    adapter: postgresql
    database: demo_app
    timeout: 5000

test:
    adapter: postgresql
    database: demo_app
    timeout: 5000
        
production:
    adapter: postgresql
    database: demo_app
    timeout: 5000